/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Om9s3FM4OLS
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"

export function chatpage() {
  return (
    <div className="grid md:grid-cols-[300px_1fr] min-h-screen w-full bg-background">
      <div className="flex flex-col border-r bg-card">
        <div className="sticky top-0 flex items-center gap-2 border-b px-4 py-3">
          <Avatar className="h-8 w-8">
            <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
            <AvatarFallback>JP</AvatarFallback>
          </Avatar>
          <div className="flex-1 truncate text-sm font-medium">Jared Palmer</div>
          <Button variant="ghost" size="icon" className="rounded-full">
            <MoveHorizontalIcon className="h-4 w-4" />
          </Button>
        </div>
        <div className="flex-1 overflow-auto">
          <div className="p-4">
            <div className="mb-4 flex items-center gap-3">
              <Avatar className="h-10 w-10">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>AC</AvatarFallback>
              </Avatar>
              <div>
                <div className="font-medium">Alex Chen</div>
                <div className="text-sm text-muted-foreground">Hey, how's it going?</div>
              </div>
            </div>
            <div className="mb-4 flex items-center gap-3">
              <Avatar className="h-10 w-10">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div>
                <div className="font-medium">Jane Doe</div>
                <div className="text-sm text-muted-foreground">Just wanted to check in.</div>
              </div>
            </div>
            <div className="mb-4 flex items-center gap-3">
              <Avatar className="h-10 w-10">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>EM</AvatarFallback>
              </Avatar>
              <div>
                <div className="font-medium">Emily Martinez</div>
                <div className="text-sm text-muted-foreground">Did you see the new update?</div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex flex-col">
        <div className="sticky top-0 flex items-center gap-2 border-b bg-card px-4 py-3">
          <Avatar className="h-8 w-8">
            <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
            <AvatarFallback>AC</AvatarFallback>
          </Avatar>
          <div className="flex-1 truncate text-sm font-medium">Alex Chen</div>
          <Button variant="ghost" size="icon" className="rounded-full">
            <MoveHorizontalIcon className="h-4 w-4" />
          </Button>
        </div>
        <div className="flex-1 overflow-auto p-4">
          <div className="grid gap-4">
            <div className="flex items-start gap-3">
              <Avatar className="h-8 w-8">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>AC</AvatarFallback>
              </Avatar>
              <div className="rounded-lg bg-muted p-3 text-sm">
                <p>Hey, how's it going?</p>
                <div className="mt-2 text-xs text-muted-foreground">3:45 PM</div>
              </div>
            </div>
            <div className="flex items-start gap-3 justify-end">
              <div className="rounded-lg bg-primary p-3 text-sm text-primary-foreground">
                <p>I'm doing great, thanks for asking!</p>
                <div className="mt-2 text-xs text-muted-foreground">3:46 PM</div>
              </div>
              <Avatar className="h-8 w-8">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>JP</AvatarFallback>
              </Avatar>
            </div>
            <div className="flex items-start gap-3">
              <Avatar className="h-8 w-8">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>AC</AvatarFallback>
              </Avatar>
              <div className="rounded-lg bg-muted p-3 text-sm">
                <p>That's great to hear! Did you see the new update?</p>
                <div className="mt-2 text-xs text-muted-foreground">3:47 PM</div>
              </div>
            </div>
            <div className="flex items-start gap-3 justify-end">
              <div className="rounded-lg bg-primary p-3 text-sm text-primary-foreground">
                <p>No, I haven't. What's new?</p>
                <div className="mt-2 text-xs text-muted-foreground">3:48 PM</div>
              </div>
              <Avatar className="h-8 w-8">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>JP</AvatarFallback>
              </Avatar>
            </div>
          </div>
        </div>
        <div className="sticky bottom-0 bg-card px-4 py-3">
          <div className="relative">
            <Textarea
              placeholder="Type your message..."
              className="min-h-[48px] w-full rounded-2xl resize-none border border-neutral-400 bg-card px-4 py-2 pr-16 shadow-sm"
            />
            <Button type="submit" size="icon" className="absolute right-3 top-3">
              <SendIcon className="h-4 w-4" />
              <span className="sr-only">Send</span>
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}

function MoveHorizontalIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="18 8 22 12 18 16" />
      <polyline points="6 8 2 12 6 16" />
      <line x1="2" x2="22" y1="12" y2="12" />
    </svg>
  )
}


function SendIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}
